const test=require('node:test'),assert=require('node:assert/strict'),fs=require('node:fs'),vm=require('node:vm');
const C=require('../core.js');
const snapshot=JSON.parse(fs.readFileSync(require.resolve('../data/snapshot.json'),'utf8'));
const curation=JSON.parse(fs.readFileSync(require.resolve('../data/curation.json'),'utf8'));
const repo=snapshot.repositories[0], now='2026-10-01T23:34:56.246Z';
const state={collection:'all',query:'',category:'all',language:'all',license:'all',sort:'activity'};
function api(id,privateValue=false){return {full_name:id,private:privateValue,description:null,language:'Python',license:null,topics:[],stargazers_count:10,pushed_at:now,updated_at:now};}
function fakeResponse(data,status=200){return {ok:status===200,status,json:async()=>data};}
function payload(entries){return {schema_version:1,type:'repository-atlas-saved',exported_at:now,entries};}
function entry(r=repo){return {repo:r,note:'로컬 메모',user_tags:['나중에'],saved_at:now};}

test('snapshot public count, terminal empty page, curated README SHA, and recommendation isolation',()=>{
 const s=C.validateSnapshot(snapshot);assert.equal(s.repositories.filter(r=>r.collection==='stars').length,s.pages.reduce((count,page)=>count+page.count,0));assert.equal(s.repositories.filter(r=>r.collection==='recommendation').length,Object.values(curation).filter(r=>r.recommendation_reason).length);assert.equal(s.pages.at(-1).count,0);assert.equal(new Set(s.repositories.map(r=>C.key(r.id))).size,s.repositories.length);assert.ok(s.repositories.every(r=>r.readme_sha&&r.reviewed_at&&r.metadata_verified));assert.ok(s.repositories.filter(r=>r.collection==='recommendation').every(r=>r.starred_at===null));
});
test('offline JS bundle exactly matches public JSON snapshot',()=>{const context={window:{}};vm.runInNewContext(fs.readFileSync(require.resolve('../data/snapshot.js'),'utf8'),context);assert.equal(JSON.stringify(context.window.REPO_ATLAS_SNAPSHOT),JSON.stringify(snapshot));});
test('all NOASSERTION entries require separate verification despite README license statements',()=>{const rows=snapshot.repositories.filter(r=>r.license_spdx==='NOASSERTION');assert.equal(rows.length,3);for(const r of rows)assert.equal(C.licenseLabel(r),'별도 확인 필요');});
test('mobile-codex exact license and ASI research loop are editorially reviewed',()=>{const m=snapshot.repositories.find(r=>r.id==='nokryong/mobile-codex');assert.equal(C.licenseLabel(m),'GPL-3.0-only');assert.equal(m.description_original,null);const a=snapshot.repositories.find(r=>r.id==='GAIR-NLP/ASI-Evolve');assert.match(a.summary_ko,/가설→실험→분석/);assert.equal(a.description_original,null);});
test('new metadata is not represented as a verified Korean README summary',()=>{const r=C.normalizeRepo(api('owner/NewRepo'),null,now);assert.equal(r.reviewed_at,null);assert.match(r.summary_ko,/검토 대기/);assert.equal(r.starred_at,null);assert.equal(C.licenseLabel(r),'별도 확인 필요');});
test('reject non-public API metadata',()=>assert.throws(()=>C.normalizeRepo(api('owner/secret',true),null,now),/공개/));
test('safe external URLs reject XSS, credentials, protocol relatives, and GitHub host spoofing',()=>{for(const u of ['javascript:alert(1)','data:text/html,hi','//evil.test','https://user:pass@github.com/o/r','https://github.com.evil.test/o/r'])assert.equal(C.safeURL(u,true),null);assert.equal(C.safeURL('https://docs.example.org/page'),'https://docs.example.org/page');});
test('repo URL parsing and case-normalized bulk duplicates',()=>{assert.equal(C.parseRepoInput('https://github.com/Owner/Repo.git/'),'Owner/Repo');const p=C.parseRepoList('Owner/Repo\nhttps://github.com/owner/repo\nowner/other, javascript:alert(1)');assert.deepEqual(p.names,['Owner/Repo','owner/other']);assert.equal(p.duplicates,1);assert.equal(p.invalid.length,1);});
test('repo URL parsing rejects extra paths and query data',()=>{for(const s of ['https://github.com/o/r/tree/main','https://github.com/o/r?token=x','https://github.com/o/r#readme','http://github.com/o/r'])assert.throws(()=>C.parseRepoInput(s));});
test('Korean and English multi-term search includes purpose, tags, description and local notes',()=>{assert.equal(C.select(snapshot.repositories,{...state,query:'android 비공식'}).length,1);assert.ok(C.select(snapshot.repositories,{...state,query:'THREE.JS'}).some(r=>r.id==='souranyp-stack/koi-pond-garden'));const saved={[C.key(repo.id)]:{saved:true,note:'필수 프로젝트',user_tags:['특별태그']}};assert.equal(C.select(snapshot.repositories,{...state,query:'필수 특별태그'},saved)[0].id,repo.id);});
test('collection/category/language/license filters compose and unknown license remains filterable',()=>{const out=C.select(snapshot.repositories,{...state,collection:'stars',language:'Python',license:'별도 확인 필요'});assert.equal(out.length,2);assert.ok(out.every(r=>r.collection==='stars'));assert.equal(C.select(snapshot.repositories,{...state,category:'3D · 인터랙티브'}).length,1);});
test('saved collection does not confuse GitHub Stars with local save flag',()=>{assert.equal(C.select(snapshot.repositories,{...state,collection:'saved'},{}).length,0);const saved={[C.key(repo.id)]:{saved:false}};assert.equal(C.select(snapshot.repositories,{...state,collection:'saved'},saved).length,0);saved[C.key(repo.id)].saved=true;assert.equal(C.select(snapshot.repositories,{...state,collection:'saved'},saved).length,1);});
test('activity sorting uses pushed_at, never metadata updated_at or starred_at',()=>{const a={...repo,id:'o/a',name:'a',pushed_at:'2020-01-01T00:00:00Z',updated_at:now,starred_at:now};const b={...repo,id:'o/b',name:'b',pushed_at:now,updated_at:'2020-01-01T00:00:00Z'};assert.equal(C.select([a,b],state)[0].id,'o/b');});
test('star sorting and name sorting are stable and deterministic',()=>{const rows=C.select(snapshot.repositories,{...state,sort:'stars'});assert.ok(rows.every((r,i)=>!i||rows[i-1].stars>=r.stars));const byName=C.select(snapshot.repositories,{...state,sort:'name'});assert.equal(byName[0].name,'AngelSlim');});
test('snapshot validation rejects duplicates, unsafe links and incomplete page records',()=>{assert.throws(()=>C.validateSnapshot({...snapshot,repositories:[...snapshot.repositories,repo]}),/중복/);assert.throws(()=>C.validateSnapshot({...snapshot,pages:snapshot.pages.slice(0,-1)}),/끝/);assert.throws(()=>C.validateRepo({...repo,docs_url:'javascript:alert(1)'}),/URL/);assert.throws(()=>C.validateRepo({...repo,repo_url:'https://github.com/evil/other'}),/불일치/);});
test('JSON validation strips asserted Stars and editorial/API verification on unknown imported records',()=>{const [e]=C.parseImport(JSON.stringify(payload([entry()])));assert.equal(e.repo.collection,'local');assert.equal(e.repo.starred_at,null);assert.equal(e.repo.reviewed_at,null);assert.equal(e.repo.metadata_verified,false);assert.equal(e.note,'로컬 메모');});
test('invalid JSON is atomic, rejects prototype fields, oversize notes, unsafe URLs and oversized file',()=>{for(const raw of ['no json','{}',JSON.stringify({...payload([]),__proto__:null,rogue:1}),JSON.stringify(payload([{...entry(),note:'x'.repeat(4001)}])),JSON.stringify(payload([entry({...repo,docs_url:'javascript:alert(1)'})]))])assert.throws(()=>C.parseImport(raw));assert.throws(()=>C.parseImport(' '.repeat(C.MAX_IMPORT_BYTES+1)),/10MB/);assert.throws(()=>C.parseImport('{"schema_version":1,"type":"repository-atlas-saved","exported_at":"'+now+'","entries":[],"__proto__":{}}'));});
test('JSON rejects duplicate IDs case-insensitively rather than silently replacing records',()=>{assert.throws(()=>C.parseImport(JSON.stringify(payload([entry(),entry({...repo,id:repo.id.toLowerCase(),owner:repo.owner.toLowerCase(),name:repo.name.toLowerCase(),repo_url:C.repoURL(repo.id.toLowerCase())})]))),/중복/);});
test('merge preserves local notes/tags/date, deduplicates canonical ID and uses verified current data',()=>{const old={[C.key(repo.id)]:{repo,note:'보존해야 함',user_tags:['기존'],saved:true,saved_at:'2020-01-01T00:00:00Z'}};const incoming={...entry(),note:'덮어쓰면 안 됨',user_tags:['새 태그']};const m=C.mergeSaved(old,[incoming],snapshot.repositories);assert.equal(Object.keys(m).length,1);assert.equal(m[C.key(repo.id)].note,'보존해야 함');assert.deepEqual(m[C.key(repo.id)].user_tags,['기존','새 태그']);assert.equal(m[C.key(repo.id)].saved_at,'2020-01-01T00:00:00Z');assert.equal(m[C.key(repo.id)].repo.collection,'stars');assert.equal(old[C.key(repo.id)].user_tags.length,1);});
test('fetchPublicRepo uses GET without credentials and verifies public flag',async()=>{let options;const r=await C.fetchPublicRepo(async(u,o)=>{assert.equal(u,'https://api.github.com/repos/new/project');options=o;return fakeResponse(api('new/project'));},'new/project');assert.equal(options.method,'GET');assert.equal(options.credentials,'omit');assert.equal(r.metadata_verified,true);assert.equal(r.collection,'local');await assert.rejects(C.fetchPublicRepo(async()=>fakeResponse(api('new/secret',true)),'new/secret'),/공개/);});
test('public Stars paginates beyond two pages through terminal empty page',async()=>{const calls=[];const result=await C.collectStars(async(u,o)=>{calls.push(u);assert.equal(o.headers.Accept,'application/vnd.github.star+json');const page=Number(new URL(u).searchParams.get('page'));return fakeResponse(page<=3?Array.from({length:page===3?30:100},(_,i)=>({repo:api('owner/r'+((page-1)*100+i)),starred_at:now})):[]);});assert.equal(result.repositories.length,230);assert.equal(calls.length,4);assert.equal(result.pages.at(-1).count,0);});
test('API failure exposes partial collection without returning a success snapshot',async()=>{let call=0;await assert.rejects(C.collectStars(async()=>++call===1?fakeResponse([{repo:api('o/a'),starred_at:now}]):fakeResponse(null,429)),e=>{assert.match(e.message,/429/);assert.deepEqual(e.partial,{pages:1,count:1});return true;});});
test('cross-page duplicates and private records abort full sync',async()=>{let n=0;await assert.rejects(C.collectStars(async()=>fakeResponse([{repo:api(++n===1?'Owner/Repo':'owner/repo'),starred_at:now}])),/중복/);await assert.rejects(C.collectStars(async()=>fakeResponse([{repo:api('o/private',true),starred_at:now}])),/비공개/);});
test('missing star timestamps remain unknown when API returns regular repository objects',async()=>{let n=0;const x=await C.collectStars(async()=>fakeResponse(n++===0?[api('o/a')]:[]));assert.equal(x.repositories[0].starred_at,null);});
test('synthetic 5000-repository search/filter/sort and JSON import performance stays bounded',()=>{const rows=Array.from({length:5000},(_,i)=>({...repo,id:'synthetic/repo'+i,owner:'synthetic',name:'repo'+i,repo_url:'https://github.com/synthetic/repo'+i,stars:i,collection:'local',summary_ko:'테스트 전용 대량 데이터 '+i,docs_url:'https://github.com/synthetic/repo'+i,readme_url:'https://github.com/synthetic/repo'+i}));const start=performance.now();assert.equal(C.select(rows,{...state,query:'테스트',sort:'stars'}).length,5000);const parsed=C.parseImport(JSON.stringify(payload(rows.map(r=>entry(r)))));assert.equal(parsed.length,5000);const elapsed=performance.now()-start;console.log('5000 synthetic records: search/filter/sort + JSON validation '+Math.round(elapsed)+'ms');assert.ok(elapsed<2500);assert.ok(snapshot.repositories.every(r=>r.owner!=='synthetic'));});

test('typesafe framework is unique, reviewed, filterable and isolated from GitHub Stars',()=>{
 const id='awlevin/typesafe-computer-use',matches=snapshot.repositories.filter(r=>C.key(r.id)===C.key(id));assert.equal(matches.length,1);const r=matches[0];assert.equal(r.collection,'recommendation');assert.equal(r.starred_at,null);assert.equal(r.language,'Python');assert.equal(C.licenseLabel(r),'MIT');assert.equal(r.archived,false);assert.equal(r.repo_url,'https://github.com/'+id);assert.equal(r.readme_sha,'875d091f6abda81ed03252184995fbeb67a9d8b7');assert.match(r.summary_ko,/자동화 프레임워크/);assert.match(r.review_note,/베타/);assert.deepEqual(C.select(snapshot.repositories,{...state,collection:'recommendation',category:'AI · 에이전트',language:'Python',license:'MIT',query:'typesafe OCR'}).map(x=>x.id),[id]);assert.equal(C.select(snapshot.repositories,{...state,collection:'stars',query:'typesafe'}).length,0);
});

test('pdoom video is unique, searchable, reviewed and preserves asset-license boundaries',()=>{
 const id='mexicat/pdoom-video',rows=snapshot.repositories.filter(r=>C.key(r.id)===C.key(id));assert.equal(rows.length,1);const r=rows[0];
 assert.equal(r.collection,'recommendation');assert.equal(r.starred_at,null);assert.equal(r.language,'TypeScript');assert.equal(C.licenseLabel(r),'MIT');assert.equal(r.metadata_verified,true);
 assert.equal(r.description_original,'Code-rendered music video for "I\'m Upping My P(doom)"');assert.match(r.summary_ko,/코드 기반 뮤직비디오/);
 assert.equal(r.readme_sha,'945a7e85559ee98ea7b4713b6b3fb6f709325c09');assert.match(r.readme_url,/a048746d25fa0333ca884fb79fe4482b9c89250d\/README\.md$/);assert.match(r.docs_url,/a048746d25fa0333ca884fb79fe4482b9c89250d\/docs\/ENGINE\.md$/);
 assert.match(r.license_note,/음악·가사.*MIT 적용 대상이 아니/);assert.match(r.license_note,/폰트.*SIL OFL/);assert.match(r.license_note,/Giacomo Magnanini/);
 assert.deepEqual(C.select(snapshot.repositories,{...state,category:'이미지 · 영상',language:'TypeScript',license:'MIT',query:'PDOOM 타이포그래피'}).map(r=>r.id),[id]);assert.equal(C.select(snapshot.repositories,{...state,collection:'stars',query:'pdoom'}).length,0);
 assert.equal(curation[id].readme_sha,r.readme_sha);assert.equal(curation[id].reviewed_at,r.reviewed_at);
});
