// DOM logic tests use linkedom. These do NOT claim native browser layout/focus validation.
const test=require('node:test'),assert=require('node:assert/strict'),fs=require('node:fs'),vm=require('node:vm'),{parseHTML}=require('linkedom');
const C=require('../core.js'),snapshot=JSON.parse(fs.readFileSync(require.resolve('../data/snapshot.json')));
const html=fs.readFileSync(require.resolve('../index.html'),'utf8'),app=fs.readFileSync(require.resolve('../app.js'),'utf8');
const now='2026-10-01T23:34:56.246Z';
const delay=()=>new Promise(r=>setTimeout(r,150));
function setup({stored={},fetchImpl=async()=>{throw Error('Network unavailable');}}={}){
 const {window,document}=parseHTML(html);const data=new Map(Object.entries(stored));let active=document.body;
 Object.defineProperty(document,'activeElement',{get:()=>active});
 window.HTMLElement.prototype.focus=function(){active=this;};
 window.HTMLElement.prototype.scrollIntoView=function(){};
 Object.defineProperty(window.HTMLSelectElement.prototype,'value',{get(){const option=this.querySelector('option[selected]')||this.querySelector('option');return option?.value||'';},set(value){for(const option of this.querySelectorAll('option')){option.toggleAttribute('selected',option.value===value);}}});
 window.HTMLSelectElement.prototype.add=function(option){this.append(option);};
 const dialog=document.querySelector('dialog');Object.defineProperty(dialog,'open',{get(){return this.hasAttribute('open');}});dialog.showModal=function(){this.setAttribute('open','');};dialog.close=function(){this.removeAttribute('open');this.dispatchEvent(new window.Event('close'));};
 window.ArchiveCore=C;window.REPO_ATLAS_SNAPSHOT=JSON.parse(JSON.stringify(snapshot));window.fetch=fetchImpl;
 const storage={getItem:k=>data.get(k)??null,setItem:(k,v)=>data.set(k,v)};
 const context=vm.createContext({window,document,localStorage:storage,matchMedia:()=>({matches:false}),CSS:{escape:s=>s},Node:window.Node,Option:function(label,value){const o=document.createElement('option');o.textContent=label;o.value=value;return o;},setTimeout,clearTimeout,Intl,Date,URL,Blob,TextEncoder,console});
 vm.runInContext(app,context);
 const $=s=>document.querySelector(s),click=s=>$(s).click(),input=(s,value)=>{const el=$(s);el.value=value;el.dispatchEvent(new window.Event('input'));},change=(s,value)=>{const el=$(s);el.value=value;el.dispatchEvent(new window.Event('change'));};
 return {window,document,data,$,click,input,change,dialog};
}
test('initial offline render, category counts and no startup network calls',()=>{let calls=0;const x=setup({fetchImpl:async()=>{calls++;throw Error();}});assert.equal(x.$('#repo-grid').children.length,16);assert.equal(x.$('#categories [data-category="all"] small').textContent,'16');assert.match(x.$('#data-status').textContent,/동봉 스냅샷/);assert.equal(calls,0);assert.equal(x.$('#repo-grid').getAttribute('aria-busy'),'false');});
test('search, combined filters, empty result and reset work through DOM events',async()=>{const x=setup();x.input('#search','android 비공식');await delay();assert.equal(x.$('#repo-grid').children.length,1);assert.match(x.$('#repo-grid').textContent,/mobile-codex/);x.change('#language','Python');assert.match(x.$('#repo-grid').textContent,/검색 결과가 없습니다/);x.click('#reset');assert.equal(x.$('#repo-grid').children.length,16);assert.equal(x.$('#search').value,'');});
test('local save, note and personal tags restore after app reinitialization; GitHub count is unchanged',()=>{const x=setup();x.click('[data-open-id="nokryong/mobile-codex"]');x.$('#note').value='다음 실험에 필요';x.$('#user-tags').value='보존태그, 모바일';x.$('.note-actions .primary').click();x.dialog.close();assert.equal(x.$('#saved-count').textContent,'1');assert.equal(x.$('#categories [data-category="all"] small').textContent,'16');const stored=Object.fromEntries(x.data);const y=setup({stored});y.click('[data-open-id="nokryong/mobile-codex"]');assert.equal(y.$('#note').value,'다음 실험에 필요');assert.equal(y.$('#user-tags').value,'보존태그, 모바일');y.$('#detail-save').click();assert.equal(y.$('#saved-count').textContent,'0');assert.match(y.data.get('repo-atlas.saved'),/다음 실험에 필요/);});
test('render imported XSS-like note/tag as text with no injected nodes; external links stay safe',()=>{const r=snapshot.repositories[0];const stored={'repo-atlas.saved':JSON.stringify({type:'repository-atlas-local',entries:[{repo:r,note:'<img src=x onerror=alert(1)>',user_tags:['<svg onload=alert(1)>'],saved:true,saved_at:now}]})};const x=setup({stored});x.click('[data-open-id="'+r.id+'"]');assert.equal(x.$('#note').value,'<img src=x onerror=alert(1)>');assert.equal(x.document.querySelectorAll('[onerror], [onload]').length,0);for(const a of x.document.querySelectorAll('a[target="_blank"]')){assert.match(a.href,/^https:\/\//);assert.equal(a.rel,'noopener noreferrer');}});
test('native dialog markup, visible close header and close event restores invoking card in DOM logic',()=>{const x=setup();const b=x.$('[data-open-id="nokryong/mobile-codex"]');b.focus();b.click();assert.equal(x.dialog.open,true);assert.equal(x.document.activeElement.id,'dialog-close');x.click('#dialog-close');assert.equal(x.dialog.open,false);assert.equal(x.document.activeElement,b);const css=fs.readFileSync(require.resolve('../atlas.css'),'utf8');assert.match(css,/\.modal-head\{position:sticky;top:0/);});
test('failed refresh keeps existing rows and original collection timestamp, exposes partial failure',async()=>{const api={full_name:'new/repo',private:false,description:null,language:'JavaScript',license:null,topics:[],stargazers_count:1,pushed_at:now,updated_at:now};let n=0;const x=setup({fetchImpl:async()=>++n===1?{ok:true,status:200,json:async()=>[{repo:api,starred_at:now}]}:{ok:false,status:429,json:async()=>null}});const before=x.$('#repo-grid').textContent;x.click('#refresh');await delay();assert.equal(x.$('#repo-grid').textContent,before);assert.match(x.$('#data-status').textContent,/부분 수집 1개\/1페이지/);assert.match(x.$('#data-status').textContent,/2026-10-01 23:34 UTC/);assert.equal(x.data.has('repo-atlas.public-cache'),false);assert.equal(x.$('#data-alert').hidden,false);assert.match(x.$('#data-alert').textContent,/갱신 실패/);});
test('successful complete resync preserves memo and personal tags, while unknown new repo is unreviewed',async()=>{const r=snapshot.repositories[0];const api={full_name:r.id,private:false,description:'updated',language:'HTML',license:{spdx_id:'MIT'},topics:[],stargazers_count:99,pushed_at:now,updated_at:now};let n=0;const stored={'repo-atlas.saved':JSON.stringify({type:'repository-atlas-local',entries:[{repo:r,note:'keep',user_tags:['tag'],saved:true,saved_at:now}]})};const x=setup({stored,fetchImpl:async()=>({ok:true,status:200,json:async()=>n++===0?[{repo:api,starred_at:now}]:[]})});x.click('#refresh');await delay();assert.equal(x.$('#categories [data-category="all"] small').textContent,'4');assert.match(x.$('#data-status').textContent,/갱신 성공/);x.click('[data-open-id="'+r.id+'"]');assert.equal(x.$('#note').value,'keep');assert.equal(x.$('#user-tags').value,'tag');assert.match(x.$('#dialog-body').textContent,/23:49 UTC/);});
test('synthetic 2000 local entries render at most 60 cards and next page advances',()=>{const r=snapshot.repositories[0];const entries=Array.from({length:2000},(_,i)=>({repo:{...r,id:'synthetic/r'+i,name:'r'+i,owner:'synthetic',repo_url:'https://github.com/synthetic/r'+i,docs_url:'https://github.com/synthetic/r'+i,readme_url:'https://github.com/synthetic/r'+i,collection:'local',reviewed_at:null,readme_sha:null},note:'test only',user_tags:[],saved:true,saved_at:now}));const start=performance.now();const x=setup({stored:{'repo-atlas.saved':JSON.stringify({type:'repository-atlas-local',entries})}});assert.equal(x.$('#repo-grid').children.length,60);assert.equal(x.$('#pagination').hidden,false);const first=x.$('#repo-grid').firstElementChild.dataset.repoId;x.$('#pagination').lastElementChild.click();assert.notEqual(x.$('#repo-grid').firstElementChild.dataset.repoId,first);assert.equal(x.$('#repo-grid').children.length,60);console.log('2000 synthetic local entries: restore/render/page '+Math.round(performance.now()-start)+'ms');});
test('URL bulk add deduplicates inputs, reports partial success, and waits for Apply',async()=>{const api={full_name:'new/project',private:false,description:'new',language:'TypeScript',license:null,topics:[],stargazers_count:1,pushed_at:now,updated_at:now};const x=setup({fetchImpl:async()=>({ok:true,status:200,json:async()=>api})});x.click('#add-repo');x.$('#repo-input').value='new/project\nhttps://github.com/NEW/project\nbad-invalid';x.$('#dialog-body button.primary').click();await delay();assert.equal(x.$('#saved-count').textContent,'0');assert.match(x.$('#dialog-body').textContent,/완료 1개/);assert.match(x.$('#dialog-body').textContent,/중복 입력 1개/);x.$('#dialog-body > div > button:last-child').click();assert.equal(x.$('#saved-count').textContent,'1');assert.match(x.$('#repo-grid').textContent,/검토 대기/);assert.equal(x.$('[data-category="미분류"] small').textContent,'1');assert.equal(x.$('#categories [data-category="all"] small').textContent,'17');});
test('bad JSON import does not alter existing saved state',async()=>{const x=setup();x.click('[data-save-id="nokryong/mobile-codex"]');const before=x.data.get('repo-atlas.saved');Object.defineProperty(x.$('#import-file'),'files',{value:[{size:7,text:async()=>'{broken'}],configurable:true});x.$('#import-file').dispatchEvent(new x.window.Event('change'));await delay();assert.match(x.$('#dialog-title').textContent,/JSON 형식 오류/);assert.equal(x.data.get('repo-atlas.saved'),before);});

test('typesafe framework renders through category filters and opens reviewed source links',async()=>{
 const x=setup(),r=snapshot.repositories.find(r=>r.id==='awlevin/typesafe-computer-use');x.click('[data-category="AI · 에이전트"]');x.input('#search','typesafe OCR');await delay();x.click('[data-category="AI · 에이전트"]');x.change('#language','Python');x.change('#license','MIT');assert.equal(x.$('#repo-grid').children.length,1);x.click('[data-open-id="'+r.id+'"]');assert.equal(x.dialog.open,true);assert.match(x.$('#dialog-body').textContent,/자동화 프레임워크/);assert.match(x.$('#dialog-body').textContent,/내 GitHub Stars 아님/);const urls=[...x.$('#dialog-body').querySelectorAll('a')].map(a=>a.href);assert.ok(urls.includes(r.repo_url));assert.ok(urls.includes(r.readme_url));x.click('#dialog-close');assert.equal(x.dialog.open,false);x.click('#reset');assert.equal(x.$('#repo-grid').children.length,16);assert.ok(x.$('[data-open-id="'+r.id+'"]'));assert.equal(x.$('#categories [data-category="all"] small').textContent,'16');assert.equal(x.data.size,0);
});

test('category navigation replaces source collections and combines with search, filters and reset',async()=>{
 const x=setup();assert.equal(x.$('#collections'),null);assert.equal(x.$('.banner'),null);assert.equal(x.$('#category'),null);assert.equal(x.$('[data-collection]'),null);assert.equal(x.$('#categories').children.length,11);assert.equal(x.$('#data-alert').hidden,true);assert.equal(x.$('.repo-card .source-badge'),null);
 const category=x.$('[data-category="AI · 에이전트"]');category.focus();category.click();assert.equal(x.$('#repo-grid').children.length,2);assert.equal(x.document.activeElement.dataset.category,'AI · 에이전트');assert.equal(x.$('[data-category="AI · 에이전트"]').getAttribute('aria-pressed'),'true');x.change('#language','Python');assert.equal(x.$('#repo-grid').children.length,1);assert.match(x.$('#repo-grid').textContent,/typesafe/);x.input('#search','openmuse');await delay();assert.match(x.$('#repo-grid').textContent,/검색 결과가 없습니다/);x.click('#reset');assert.equal(x.$('#repo-grid').children.length,16);assert.equal(x.$('[data-category="all"]').getAttribute('aria-pressed'),'true');assert.equal(x.$('#language').value,'all');assert.equal(x.$('#search').value,'');assert.equal(x.data.size,0);
});
test('saved items remain available in the management menu without hiding other categories after reset',()=>{
 const x=setup();x.click('[data-save-id="awlevin/typesafe-computer-use"]');const savedBefore=x.data.get('repo-atlas.saved');x.$('#saved-only').checked=true;x.$('#saved-only').dispatchEvent(new x.window.Event('change'));assert.equal(x.$('#repo-grid').children.length,1);x.click('[data-category="AI · 연구"]');assert.match(x.$('#repo-grid').textContent,/검색 결과가 없습니다/);x.click('#reset');assert.equal(x.$('#repo-grid').children.length,16);assert.equal(x.$('#saved-only').checked,false);assert.equal(x.data.get('repo-atlas.saved'),savedBefore);
});
test('closing a management dialog restores focus to the visible management control',()=>{
 const x=setup();x.$('#data-info').focus();x.click('#data-info');assert.equal(x.dialog.open,true);x.click('#dialog-close');assert.equal(x.dialog.open,false);assert.equal(x.document.activeElement,x.$('#manage summary'));
});
